/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include <ql/time/date.hpp>
#include <ql/time/period.hpp>
#include <ql/time/timeunit.hpp>
#include <ql/time/weekday.hpp>

